linters:
  enable:
    - gofmt
    - govet
    - goimports
    - gosimple
    - staticcheck
    - errcheck
    - ineffassign
    - typecheck
    - misspell
    - gosec
    - unconvert
    - unparam
    - whitespace

linters-settings:
  gofmt:
    simplify: true
  govet:
    check-shadowing: true
  goimports:
    local-prefixes: github.com/outofcoffee/go-xml-example-generator
  gosec:
    excludes:
      - G404  # Ignore weak random number generator warning as we're only generating example data

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

run:
  deadline: 5m
  tests: true
  skip-dirs:
    - vendor/ 