name: Build and Test

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.4'
          check-latest: true

      - name: Lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: latest

      - name: Build
        run: go build -v ./...

      - name: Test with Coverage
        run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Changelog Entries
        uses: release-tools/since@707ab359a9d7f14e5d19126ec19e3fe218b8cbcc
        with:
          output-file: version_changelog.txt

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: version_changelog.txt
          draft: false
          prerelease: false
